<?php 
 
 	@define('p_1', 'Ciudades');
 	@define('p_2', 'Clientes');
 	@define('p_3', 'Productos');
	@define('p_4', 'Ordenes');
	@define('p_5', 'Inicio');
	@define('p_6', 'Ciudades');
	@define('p_7', 'Nombre');
	@define('p_8', 'Opciones');
	@define('p_9', 'Crear');
	@define('p_10', 'Crear ciudades');
	@define('p_11', 'Nombre');
	@define('p_12', 'Guardar');
	@define('p_13', 'Exito');
	@define('p_14', 'Registro exitoso');
	@define('p_15', 'Error');
	@define('p_16', 'Error en el registro');
	@define('p_17', 'Edit ciudades');
	@define('p_18', 'Eliminacion exitosa');
	@define('p_19', 'Error al eliminar');
	@define('p_20', 'Modificacion exitosa');
	@define('p_21', 'Error al modificar');
	@define('p_22', 'Cliente');
	@define('p_23', 'Numero');
	@define('p_24', 'Nombre');
	@define('p_25', 'Cumpleaños');
	@define('p_26', 'Celular');
	@define('p_27', 'Ciudad');
	@define('p_28', 'Crear cliente');
	@define('p_29', 'Cliente creado');
	@define('p_30', 'Cliente no creado');
	@define('p_31', 'Cliente eliminado');
	@define('p_32', 'Cliente no eliminado');
	@define('p_33', 'Producto');
	@define('p_34', 'Descripcion');
	@define('p_35', 'Cantidad');
	@define('p_36', 'Valor');
	@define('p_37', 'Crear producto');
	@define('p_38', 'Editar cliente');
	@define('p_39', 'Precio');
	@define('p_40', 'Cantidad');
	@define('p_41', 'Descripcion');
	@define('p_42', 'Producto creado');
	@define('p_43', 'Error al crear el producto');
	@define('p_44', 'Editar producto');
	@define('p_45', 'Producto editado');
	@define('p_46', 'Error al editar');
	@define('p_47', 'Producto Eliminado');
	@define('p_48', 'Producto no eliminado');
	@define('p_49', 'Ordenes');
	@define('p_50', 'Agregar orden');
	@define('p_51', 'Cliente');
	@define('p_52', 'Producto');
	@define('p_53', 'Agregar');
	@define('p_54', 'Descripcion');
	@define('p_55', 'Opcion');
	@define('p_56', 'Valor');
	@define('p_57', 'Agregado');
	@define('p_58', 'Eliminado');
	@define('p_59', 'Producto eliminado');
	@define('p_60', 'Erro al elimnar producto');
	@define('p_61', 'Cliente Actualizado');
	@define('p_62', 'Error actualizar al cliente');
	@define('p_63', 'Cliente');
	@define('p_64', 'Total');
	@define('p_65', 'Fecha creacion');
	@define('p_66', 'Fecha Entrega');
	@define('p_67', 'Eliminacion exitosa');
	@define('p_68', 'Error al eliminar');
	@define('p_69', 'Entrega actualizada');
	@define('p_70', 'Error actualizar entrega');
	@define('p_71', 'Editar orden');
?>